[project]
name = "nyc-holiday-and-pay-calendar"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "pdf2image>=1.17.0",
    "requests>=2.32.5",
    "pdfplumber>=0.9.0",
    "pandas>=2.0.0",
]
